name: Deploy via SSH
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 192.46.215.231
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}

          script: |
            cd ~/var/www
            git clone https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com:Krushnkant/Elearn-Knowledgewood.git
            echo "Deployment Successful"
